import { displayMenu } from "./display-menu";
import { displayFooter } from "./display-footer";
import { randomBackground } from "./background";
import { displayUpload } from "./display-upload";
import { displayImages } from "./display-gallery";
displayMenu();
displayFooter();
displayUpload(10);
displayImages();
randomBackground(5);